// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlc

import (
	"context"
)

const listAgentsByProject = `-- name: ListAgentsByProject :many
select id, project_id, name, role_id, executor_profile_id, enabled, created_at, updated_at
from agents
where project_id = $1
order by created_at desc
`

func (q *Queries) ListAgentsByProject(ctx context.Context, projectID string) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.RoleID,
			&i.ExecutorProfileID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
