// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approvals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApproval = `-- name: CreateApproval :one
insert into approvals (
  id,
  mission_id,
  run_id,
  node_run_id,
  action,
  subject_type,
  subject_id,
  intent_snapshot_json,
  intent_hash,
  status,
  comment,
  created_by,
  decided_by
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
returning id, mission_id, run_id, node_run_id, action, subject_type, subject_id, intent_snapshot_json, intent_hash, status, comment, created_by, decided_by, created_at, decided_at
`

type CreateApprovalParams struct {
	ID                 string      `json:"id"`
	MissionID          pgtype.Text `json:"mission_id"`
	RunID              pgtype.Text `json:"run_id"`
	NodeRunID          pgtype.Text `json:"node_run_id"`
	Action             string      `json:"action"`
	SubjectType        string      `json:"subject_type"`
	SubjectID          string      `json:"subject_id"`
	IntentSnapshotJson []byte      `json:"intent_snapshot_json"`
	IntentHash         string      `json:"intent_hash"`
	Status             string      `json:"status"`
	Comment            pgtype.Text `json:"comment"`
	CreatedBy          string      `json:"created_by"`
	DecidedBy          pgtype.Text `json:"decided_by"`
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.ID,
		arg.MissionID,
		arg.RunID,
		arg.NodeRunID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.IntentSnapshotJson,
		arg.IntentHash,
		arg.Status,
		arg.Comment,
		arg.CreatedBy,
		arg.DecidedBy,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.RunID,
		&i.NodeRunID,
		&i.Action,
		&i.SubjectType,
		&i.SubjectID,
		&i.IntentSnapshotJson,
		&i.IntentHash,
		&i.Status,
		&i.Comment,
		&i.CreatedBy,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getApproval = `-- name: GetApproval :one
select id, mission_id, run_id, node_run_id, action, subject_type, subject_id, intent_snapshot_json, intent_hash, status, comment, created_by, decided_by, created_at, decided_at
from approvals
where id = $1
`

func (q *Queries) GetApproval(ctx context.Context, id string) (Approval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.RunID,
		&i.NodeRunID,
		&i.Action,
		&i.SubjectType,
		&i.SubjectID,
		&i.IntentSnapshotJson,
		&i.IntentHash,
		&i.Status,
		&i.Comment,
		&i.CreatedBy,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listApprovalIDsByMission = `-- name: ListApprovalIDsByMission :many
select id
from approvals
where mission_id = $1
order by created_at desc
`

func (q *Queries) ListApprovalIDsByMission(ctx context.Context, missionID pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, listApprovalIDsByMission, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalsByMission = `-- name: ListApprovalsByMission :many
select id, mission_id, run_id, node_run_id, action, subject_type, subject_id, intent_snapshot_json, intent_hash, status, comment, created_by, decided_by, created_at, decided_at
from approvals
where mission_id = $1
order by created_at desc
`

func (q *Queries) ListApprovalsByMission(ctx context.Context, missionID pgtype.Text) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovalsByMission, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Approval
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.RunID,
			&i.NodeRunID,
			&i.Action,
			&i.SubjectType,
			&i.SubjectID,
			&i.IntentSnapshotJson,
			&i.IntentHash,
			&i.Status,
			&i.Comment,
			&i.CreatedBy,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
