// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archives.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMissionArchive = `-- name: CreateMissionArchive :one
insert into mission_archives (
  id,
  mission_id,
  status,
  manifest_object_key,
  bundle_object_key,
  hash
) values (
  $1, $2, $3, $4, $5, $6
)
returning id, mission_id, status, manifest_object_key, bundle_object_key, hash, created_at, finished_at
`

type CreateMissionArchiveParams struct {
	ID                string      `json:"id"`
	MissionID         string      `json:"mission_id"`
	Status            string      `json:"status"`
	ManifestObjectKey pgtype.Text `json:"manifest_object_key"`
	BundleObjectKey   pgtype.Text `json:"bundle_object_key"`
	Hash              pgtype.Text `json:"hash"`
}

func (q *Queries) CreateMissionArchive(ctx context.Context, arg CreateMissionArchiveParams) (MissionArchive, error) {
	row := q.db.QueryRow(ctx, createMissionArchive,
		arg.ID,
		arg.MissionID,
		arg.Status,
		arg.ManifestObjectKey,
		arg.BundleObjectKey,
		arg.Hash,
	)
	var i MissionArchive
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Status,
		&i.ManifestObjectKey,
		&i.BundleObjectKey,
		&i.Hash,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getMissionArchiveByMission = `-- name: GetMissionArchiveByMission :one
select id, mission_id, status, manifest_object_key, bundle_object_key, hash, created_at, finished_at
from mission_archives
where mission_id = $1
order by created_at desc
limit 1
`

func (q *Queries) GetMissionArchiveByMission(ctx context.Context, missionID string) (MissionArchive, error) {
	row := q.db.QueryRow(ctx, getMissionArchiveByMission, missionID)
	var i MissionArchive
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Status,
		&i.ManifestObjectKey,
		&i.BundleObjectKey,
		&i.Hash,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listAdoptedDocumentVersionIDsByMission = `-- name: ListAdoptedDocumentVersionIDsByMission :many
select current_adopted_version_id
from shared_documents
where mission_id = $1
  and current_adopted_version_id is not null
order by updated_at desc
`

func (q *Queries) ListAdoptedDocumentVersionIDsByMission(ctx context.Context, missionID string) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listAdoptedDocumentVersionIDsByMission, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var current_adopted_version_id pgtype.Text
		if err := rows.Scan(&current_adopted_version_id); err != nil {
			return nil, err
		}
		items = append(items, current_adopted_version_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissionDecisionIDs = `-- name: ListMissionDecisionIDs :many
select id
from mission_decisions
where mission_id = $1
order by created_at desc
`

func (q *Queries) ListMissionDecisionIDs(ctx context.Context, missionID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMissionDecisionIDs, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeSummaryKeysByMission = `-- name: ListRuntimeSummaryKeysByMission :many
select distinct ('runtime/' || executor_session_id || '.json') as object_key
from agent_runtime_events
where mission_id = $1
order by object_key asc
`

func (q *Queries) ListRuntimeSummaryKeysByMission(ctx context.Context, missionID string) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listRuntimeSummaryKeysByMission, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var object_key interface{}
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMissionArchiveStatus = `-- name: UpdateMissionArchiveStatus :one
update mission_archives
set
  status = $2,
  manifest_object_key = $3,
  bundle_object_key = $4,
  hash = $5,
  finished_at = case when $2 = 'uploaded' then now() else finished_at end
where id = $1
returning id, mission_id, status, manifest_object_key, bundle_object_key, hash, created_at, finished_at
`

type UpdateMissionArchiveStatusParams struct {
	ID                string      `json:"id"`
	Status            string      `json:"status"`
	ManifestObjectKey pgtype.Text `json:"manifest_object_key"`
	BundleObjectKey   pgtype.Text `json:"bundle_object_key"`
	Hash              pgtype.Text `json:"hash"`
}

func (q *Queries) UpdateMissionArchiveStatus(ctx context.Context, arg UpdateMissionArchiveStatusParams) (MissionArchive, error) {
	row := q.db.QueryRow(ctx, updateMissionArchiveStatus,
		arg.ID,
		arg.Status,
		arg.ManifestObjectKey,
		arg.BundleObjectKey,
		arg.Hash,
	)
	var i MissionArchive
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Status,
		&i.ManifestObjectKey,
		&i.BundleObjectKey,
		&i.Hash,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
