// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authz.sql

package sqlc

import (
	"context"
)

const getProjectAccessGrant = `-- name: GetProjectAccessGrant :one
select id, project_id, actor_user_id, can_manage_mission, can_view_transcripts, can_export_transcripts, can_manage_archive, created_at, updated_at
from project_access_grants
where project_id = $1 and actor_user_id = $2
`

type GetProjectAccessGrantParams struct {
	ProjectID   string `json:"project_id"`
	ActorUserID string `json:"actor_user_id"`
}

func (q *Queries) GetProjectAccessGrant(ctx context.Context, arg GetProjectAccessGrantParams) (ProjectAccessGrant, error) {
	row := q.db.QueryRow(ctx, getProjectAccessGrant, arg.ProjectID, arg.ActorUserID)
	var i ProjectAccessGrant
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ActorUserID,
		&i.CanManageMission,
		&i.CanViewTranscripts,
		&i.CanExportTranscripts,
		&i.CanManageArchive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectAccessGrant = `-- name: UpsertProjectAccessGrant :one
insert into project_access_grants (
  id,
  project_id,
  actor_user_id,
  can_manage_mission,
  can_view_transcripts,
  can_export_transcripts,
  can_manage_archive
) values (
  $1, $2, $3, $4, $5, $6, $7
)
on conflict (project_id, actor_user_id) do update
set
  can_manage_mission = excluded.can_manage_mission,
  can_view_transcripts = excluded.can_view_transcripts,
  can_export_transcripts = excluded.can_export_transcripts,
  can_manage_archive = excluded.can_manage_archive,
  updated_at = now()
returning id, project_id, actor_user_id, can_manage_mission, can_view_transcripts, can_export_transcripts, can_manage_archive, created_at, updated_at
`

type UpsertProjectAccessGrantParams struct {
	ID                   string `json:"id"`
	ProjectID            string `json:"project_id"`
	ActorUserID          string `json:"actor_user_id"`
	CanManageMission     bool   `json:"can_manage_mission"`
	CanViewTranscripts   bool   `json:"can_view_transcripts"`
	CanExportTranscripts bool   `json:"can_export_transcripts"`
	CanManageArchive     bool   `json:"can_manage_archive"`
}

func (q *Queries) UpsertProjectAccessGrant(ctx context.Context, arg UpsertProjectAccessGrantParams) (ProjectAccessGrant, error) {
	row := q.db.QueryRow(ctx, upsertProjectAccessGrant,
		arg.ID,
		arg.ProjectID,
		arg.ActorUserID,
		arg.CanManageMission,
		arg.CanViewTranscripts,
		arg.CanExportTranscripts,
		arg.CanManageArchive,
	)
	var i ProjectAccessGrant
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ActorUserID,
		&i.CanManageMission,
		&i.CanViewTranscripts,
		&i.CanExportTranscripts,
		&i.CanManageArchive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
