// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discussions.sql

package sqlc

import (
	"context"
)

const createDiscussionRound = `-- name: CreateDiscussionRound :one
insert into discussion_rounds (
  id,
  session_id,
  round_no,
  prompt_summary,
  participant_agent_ids_json,
  summary,
  open_questions_json,
  conflicts_json,
  conclusion_json,
  adopted_document_version_ids_json
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
returning id, session_id, round_no, prompt_summary, participant_agent_ids_json, summary, open_questions_json, conflicts_json, conclusion_json, adopted_document_version_ids_json, created_at
`

type CreateDiscussionRoundParams struct {
	ID                            string `json:"id"`
	SessionID                     string `json:"session_id"`
	RoundNo                       int32  `json:"round_no"`
	PromptSummary                 string `json:"prompt_summary"`
	ParticipantAgentIdsJson       []byte `json:"participant_agent_ids_json"`
	Summary                       string `json:"summary"`
	OpenQuestionsJson             []byte `json:"open_questions_json"`
	ConflictsJson                 []byte `json:"conflicts_json"`
	ConclusionJson                []byte `json:"conclusion_json"`
	AdoptedDocumentVersionIdsJson []byte `json:"adopted_document_version_ids_json"`
}

func (q *Queries) CreateDiscussionRound(ctx context.Context, arg CreateDiscussionRoundParams) (DiscussionRound, error) {
	row := q.db.QueryRow(ctx, createDiscussionRound,
		arg.ID,
		arg.SessionID,
		arg.RoundNo,
		arg.PromptSummary,
		arg.ParticipantAgentIdsJson,
		arg.Summary,
		arg.OpenQuestionsJson,
		arg.ConflictsJson,
		arg.ConclusionJson,
		arg.AdoptedDocumentVersionIdsJson,
	)
	var i DiscussionRound
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RoundNo,
		&i.PromptSummary,
		&i.ParticipantAgentIdsJson,
		&i.Summary,
		&i.OpenQuestionsJson,
		&i.ConflictsJson,
		&i.ConclusionJson,
		&i.AdoptedDocumentVersionIdsJson,
		&i.CreatedAt,
	)
	return i, err
}

const createDiscussionSession = `-- name: CreateDiscussionSession :one
insert into discussion_sessions (
  id,
  mission_id,
  topic,
  status,
  initiated_by_agent_id
) values (
  $1, $2, $3, $4, $5
)
returning id, mission_id, topic, status, initiated_by_agent_id, created_at, closed_at
`

type CreateDiscussionSessionParams struct {
	ID                 string `json:"id"`
	MissionID          string `json:"mission_id"`
	Topic              string `json:"topic"`
	Status             string `json:"status"`
	InitiatedByAgentID string `json:"initiated_by_agent_id"`
}

func (q *Queries) CreateDiscussionSession(ctx context.Context, arg CreateDiscussionSessionParams) (DiscussionSession, error) {
	row := q.db.QueryRow(ctx, createDiscussionSession,
		arg.ID,
		arg.MissionID,
		arg.Topic,
		arg.Status,
		arg.InitiatedByAgentID,
	)
	var i DiscussionSession
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Topic,
		&i.Status,
		&i.InitiatedByAgentID,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getNextDiscussionRoundNumber = `-- name: GetNextDiscussionRoundNumber :one
select coalesce(max(round_no), 0)::int4 + 1
from discussion_rounds
where session_id = $1
`

func (q *Queries) GetNextDiscussionRoundNumber(ctx context.Context, sessionID string) (int32, error) {
	row := q.db.QueryRow(ctx, getNextDiscussionRoundNumber, sessionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listDiscussionSessionsByMission = `-- name: ListDiscussionSessionsByMission :many
select id, mission_id, topic, status, initiated_by_agent_id, created_at, closed_at
from discussion_sessions
where mission_id = $1
order by created_at desc
`

func (q *Queries) ListDiscussionSessionsByMission(ctx context.Context, missionID string) ([]DiscussionSession, error) {
	rows, err := q.db.Query(ctx, listDiscussionSessionsByMission, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscussionSession
	for rows.Next() {
		var i DiscussionSession
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.Topic,
			&i.Status,
			&i.InitiatedByAgentID,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
