// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAdoptedSharedDocumentVersions = `-- name: ClearAdoptedSharedDocumentVersions :exec
update shared_document_versions
set status = 'proposed'
where document_id = $1 and status = 'adopted'
`

func (q *Queries) ClearAdoptedSharedDocumentVersions(ctx context.Context, documentID string) error {
	_, err := q.db.Exec(ctx, clearAdoptedSharedDocumentVersions, documentID)
	return err
}

const createSharedDocument = `-- name: CreateSharedDocument :one
insert into shared_documents (
  id,
  mission_id,
  kind,
  title,
  current_adopted_version_id
) values (
  $1, $2, $3, $4, $5
)
returning id, mission_id, kind, title, current_adopted_version_id, created_at, updated_at
`

type CreateSharedDocumentParams struct {
	ID                      string      `json:"id"`
	MissionID               string      `json:"mission_id"`
	Kind                    string      `json:"kind"`
	Title                   string      `json:"title"`
	CurrentAdoptedVersionID pgtype.Text `json:"current_adopted_version_id"`
}

func (q *Queries) CreateSharedDocument(ctx context.Context, arg CreateSharedDocumentParams) (SharedDocument, error) {
	row := q.db.QueryRow(ctx, createSharedDocument,
		arg.ID,
		arg.MissionID,
		arg.Kind,
		arg.Title,
		arg.CurrentAdoptedVersionID,
	)
	var i SharedDocument
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Kind,
		&i.Title,
		&i.CurrentAdoptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSharedDocumentVersion = `-- name: CreateSharedDocumentVersion :one
insert into shared_document_versions (
  id,
  document_id,
  version,
  parent_version_id,
  status,
  content_format,
  storage_kind,
  object_key,
  content_hash,
  content_text,
  produced_by_agent_id,
  produced_by_run_id,
  source_round_id
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
returning id, document_id, version, parent_version_id, status, content_format, storage_kind, object_key, content_hash, content_text, produced_by_agent_id, produced_by_run_id, source_round_id, created_at
`

type CreateSharedDocumentVersionParams struct {
	ID                string      `json:"id"`
	DocumentID        string      `json:"document_id"`
	Version           int32       `json:"version"`
	ParentVersionID   pgtype.Text `json:"parent_version_id"`
	Status            string      `json:"status"`
	ContentFormat     string      `json:"content_format"`
	StorageKind       string      `json:"storage_kind"`
	ObjectKey         pgtype.Text `json:"object_key"`
	ContentHash       string      `json:"content_hash"`
	ContentText       string      `json:"content_text"`
	ProducedByAgentID pgtype.Text `json:"produced_by_agent_id"`
	ProducedByRunID   pgtype.Text `json:"produced_by_run_id"`
	SourceRoundID     pgtype.Text `json:"source_round_id"`
}

func (q *Queries) CreateSharedDocumentVersion(ctx context.Context, arg CreateSharedDocumentVersionParams) (SharedDocumentVersion, error) {
	row := q.db.QueryRow(ctx, createSharedDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.Version,
		arg.ParentVersionID,
		arg.Status,
		arg.ContentFormat,
		arg.StorageKind,
		arg.ObjectKey,
		arg.ContentHash,
		arg.ContentText,
		arg.ProducedByAgentID,
		arg.ProducedByRunID,
		arg.SourceRoundID,
	)
	var i SharedDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.ParentVersionID,
		&i.Status,
		&i.ContentFormat,
		&i.StorageKind,
		&i.ObjectKey,
		&i.ContentHash,
		&i.ContentText,
		&i.ProducedByAgentID,
		&i.ProducedByRunID,
		&i.SourceRoundID,
		&i.CreatedAt,
	)
	return i, err
}

const getNextSharedDocumentVersionNumber = `-- name: GetNextSharedDocumentVersionNumber :one
select coalesce(max(version), 0)::int4 + 1
from shared_document_versions
where document_id = $1
`

func (q *Queries) GetNextSharedDocumentVersionNumber(ctx context.Context, documentID string) (int32, error) {
	row := q.db.QueryRow(ctx, getNextSharedDocumentVersionNumber, documentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getSharedDocument = `-- name: GetSharedDocument :one
select id, mission_id, kind, title, current_adopted_version_id, created_at, updated_at
from shared_documents
where id = $1 and mission_id = $2
`

type GetSharedDocumentParams struct {
	ID        string `json:"id"`
	MissionID string `json:"mission_id"`
}

func (q *Queries) GetSharedDocument(ctx context.Context, arg GetSharedDocumentParams) (SharedDocument, error) {
	row := q.db.QueryRow(ctx, getSharedDocument, arg.ID, arg.MissionID)
	var i SharedDocument
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Kind,
		&i.Title,
		&i.CurrentAdoptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSharedDocumentVersion = `-- name: GetSharedDocumentVersion :one
select id, document_id, version, parent_version_id, status, content_format, storage_kind, object_key, content_hash, content_text, produced_by_agent_id, produced_by_run_id, source_round_id, created_at
from shared_document_versions
where id = $1
`

func (q *Queries) GetSharedDocumentVersion(ctx context.Context, id string) (SharedDocumentVersion, error) {
	row := q.db.QueryRow(ctx, getSharedDocumentVersion, id)
	var i SharedDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.ParentVersionID,
		&i.Status,
		&i.ContentFormat,
		&i.StorageKind,
		&i.ObjectKey,
		&i.ContentHash,
		&i.ContentText,
		&i.ProducedByAgentID,
		&i.ProducedByRunID,
		&i.SourceRoundID,
		&i.CreatedAt,
	)
	return i, err
}

const listSharedDocumentVersions = `-- name: ListSharedDocumentVersions :many
select id, document_id, version, parent_version_id, status, content_format, storage_kind, object_key, content_hash, content_text, produced_by_agent_id, produced_by_run_id, source_round_id, created_at
from shared_document_versions
where document_id = $1
order by version asc
`

func (q *Queries) ListSharedDocumentVersions(ctx context.Context, documentID string) ([]SharedDocumentVersion, error) {
	rows, err := q.db.Query(ctx, listSharedDocumentVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SharedDocumentVersion
	for rows.Next() {
		var i SharedDocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Version,
			&i.ParentVersionID,
			&i.Status,
			&i.ContentFormat,
			&i.StorageKind,
			&i.ObjectKey,
			&i.ContentHash,
			&i.ContentText,
			&i.ProducedByAgentID,
			&i.ProducedByRunID,
			&i.SourceRoundID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedDocumentsByMission = `-- name: ListSharedDocumentsByMission :many
select id, mission_id, kind, title, current_adopted_version_id, created_at, updated_at
from shared_documents
where mission_id = $1
order by updated_at desc
`

func (q *Queries) ListSharedDocumentsByMission(ctx context.Context, missionID string) ([]SharedDocument, error) {
	rows, err := q.db.Query(ctx, listSharedDocumentsByMission, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SharedDocument
	for rows.Next() {
		var i SharedDocument
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.Kind,
			&i.Title,
			&i.CurrentAdoptedVersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSharedDocumentCurrentAdoptedVersion = `-- name: SetSharedDocumentCurrentAdoptedVersion :one
update shared_documents
set
  current_adopted_version_id = $2,
  updated_at = now()
where id = $1
returning id, mission_id, kind, title, current_adopted_version_id, created_at, updated_at
`

type SetSharedDocumentCurrentAdoptedVersionParams struct {
	ID                      string      `json:"id"`
	CurrentAdoptedVersionID pgtype.Text `json:"current_adopted_version_id"`
}

func (q *Queries) SetSharedDocumentCurrentAdoptedVersion(ctx context.Context, arg SetSharedDocumentCurrentAdoptedVersionParams) (SharedDocument, error) {
	row := q.db.QueryRow(ctx, setSharedDocumentCurrentAdoptedVersion, arg.ID, arg.CurrentAdoptedVersionID)
	var i SharedDocument
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Kind,
		&i.Title,
		&i.CurrentAdoptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSharedDocumentVersionStatus = `-- name: UpdateSharedDocumentVersionStatus :one
update shared_document_versions
set status = $2
where id = $1
returning id, document_id, version, parent_version_id, status, content_format, storage_kind, object_key, content_hash, content_text, produced_by_agent_id, produced_by_run_id, source_round_id, created_at
`

type UpdateSharedDocumentVersionStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSharedDocumentVersionStatus(ctx context.Context, arg UpdateSharedDocumentVersionStatusParams) (SharedDocumentVersion, error) {
	row := q.db.QueryRow(ctx, updateSharedDocumentVersionStatus, arg.ID, arg.Status)
	var i SharedDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.ParentVersionID,
		&i.Status,
		&i.ContentFormat,
		&i.StorageKind,
		&i.ObjectKey,
		&i.ContentHash,
		&i.ContentText,
		&i.ProducedByAgentID,
		&i.ProducedByRunID,
		&i.SourceRoundID,
		&i.CreatedAt,
	)
	return i, err
}
