// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: missions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMission = `-- name: CreateMission :one
insert into missions (
  id,
  project_id,
  title,
  description,
  source_type,
  status,
  admin_agent_id,
  team_id,
  repo_binding_id,
  created_by
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
returning id, project_id, title, description, source_type, status, admin_agent_id, team_id, repo_binding_id, created_by, created_at, updated_at, completed_at
`

type CreateMissionParams struct {
	ID            string      `json:"id"`
	ProjectID     string      `json:"project_id"`
	Title         string      `json:"title"`
	Description   pgtype.Text `json:"description"`
	SourceType    string      `json:"source_type"`
	Status        string      `json:"status"`
	AdminAgentID  string      `json:"admin_agent_id"`
	TeamID        pgtype.Text `json:"team_id"`
	RepoBindingID pgtype.Text `json:"repo_binding_id"`
	CreatedBy     string      `json:"created_by"`
}

func (q *Queries) CreateMission(ctx context.Context, arg CreateMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, createMission,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.SourceType,
		arg.Status,
		arg.AdminAgentID,
		arg.TeamID,
		arg.RepoBindingID,
		arg.CreatedBy,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.SourceType,
		&i.Status,
		&i.AdminAgentID,
		&i.TeamID,
		&i.RepoBindingID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createMissionDecision = `-- name: CreateMissionDecision :one
insert into mission_decisions (
  id,
  mission_id,
  decided_by_agent_id,
  decision,
  summary,
  related_task_item_id,
  related_document_version_ids_json,
  related_repo_candidate_ids_json
) values (
  $1, $2, $3, $4, $5, $6, $7, $8
)
returning id, mission_id, decided_by_agent_id, decision, summary, related_task_item_id, related_document_version_ids_json, related_repo_candidate_ids_json, created_at
`

type CreateMissionDecisionParams struct {
	ID                            string      `json:"id"`
	MissionID                     string      `json:"mission_id"`
	DecidedByAgentID              string      `json:"decided_by_agent_id"`
	Decision                      string      `json:"decision"`
	Summary                       string      `json:"summary"`
	RelatedTaskItemID             pgtype.Text `json:"related_task_item_id"`
	RelatedDocumentVersionIdsJson []byte      `json:"related_document_version_ids_json"`
	RelatedRepoCandidateIdsJson   []byte      `json:"related_repo_candidate_ids_json"`
}

func (q *Queries) CreateMissionDecision(ctx context.Context, arg CreateMissionDecisionParams) (MissionDecision, error) {
	row := q.db.QueryRow(ctx, createMissionDecision,
		arg.ID,
		arg.MissionID,
		arg.DecidedByAgentID,
		arg.Decision,
		arg.Summary,
		arg.RelatedTaskItemID,
		arg.RelatedDocumentVersionIdsJson,
		arg.RelatedRepoCandidateIdsJson,
	)
	var i MissionDecision
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.DecidedByAgentID,
		&i.Decision,
		&i.Summary,
		&i.RelatedTaskItemID,
		&i.RelatedDocumentVersionIdsJson,
		&i.RelatedRepoCandidateIdsJson,
		&i.CreatedAt,
	)
	return i, err
}

const getMission = `-- name: GetMission :one
select id, project_id, title, description, source_type, status, admin_agent_id, team_id, repo_binding_id, created_by, created_at, updated_at, completed_at
from missions
where id = $1 and project_id = $2
`

type GetMissionParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetMission(ctx context.Context, arg GetMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, getMission, arg.ID, arg.ProjectID)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.SourceType,
		&i.Status,
		&i.AdminAgentID,
		&i.TeamID,
		&i.RepoBindingID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateMissionStatus = `-- name: UpdateMissionStatus :one
update missions
set
  status = $2,
  updated_at = now(),
  completed_at = case when $2 = 'completed' then now() else completed_at end
where id = $1
returning id, project_id, title, description, source_type, status, admin_agent_id, team_id, repo_binding_id, created_by, created_at, updated_at, completed_at
`

type UpdateMissionStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateMissionStatus(ctx context.Context, arg UpdateMissionStatusParams) (Mission, error) {
	row := q.db.QueryRow(ctx, updateMissionStatus, arg.ID, arg.Status)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.SourceType,
		&i.Status,
		&i.AdminAgentID,
		&i.TeamID,
		&i.RepoBindingID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
