// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                string             `json:"id"`
	ProjectID         string             `json:"project_id"`
	Name              string             `json:"name"`
	RoleID            string             `json:"role_id"`
	ExecutorProfileID string             `json:"executor_profile_id"`
	Enabled           bool               `json:"enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AgentAdminPolicy struct {
	ID                                      string             `json:"id"`
	ProjectID                               string             `json:"project_id"`
	RequirePlanAdoptionBeforeImplementation bool               `json:"require_plan_adoption_before_implementation"`
	RequireTestCheckpointBeforeComplete     bool               `json:"require_test_checkpoint_before_complete"`
	RequireReviewCheckpointBeforeComplete   bool               `json:"require_review_checkpoint_before_complete"`
	AllowAutoCreateTasks                    bool               `json:"allow_auto_create_tasks"`
	AllowAutoAssignTasks                    bool               `json:"allow_auto_assign_tasks"`
	AllowAutoTriggerDownstream              bool               `json:"allow_auto_trigger_downstream"`
	AllowCompleteWithOpenRisks              bool               `json:"allow_complete_with_open_risks"`
	CreatedAt                               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                               pgtype.Timestamptz `json:"updated_at"`
}

type AgentPresence struct {
	AgentID                  string             `json:"agent_id"`
	Availability             string             `json:"availability"`
	CurrentMissionID         pgtype.Text        `json:"current_mission_id"`
	CurrentTaskItemID        pgtype.Text        `json:"current_task_item_id"`
	CurrentExecutorSessionID pgtype.Text        `json:"current_executor_session_id"`
	LastHeartbeatAt          pgtype.Timestamptz `json:"last_heartbeat_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type AgentRuntimeEvent struct {
	ID                string             `json:"id"`
	MissionID         string             `json:"mission_id"`
	AgentID           string             `json:"agent_id"`
	ExecutorSessionID string             `json:"executor_session_id"`
	RunID             pgtype.Text        `json:"run_id"`
	NodeRunID         pgtype.Text        `json:"node_run_id"`
	TaskItemID        pgtype.Text        `json:"task_item_id"`
	Level             string             `json:"level"`
	Category          string             `json:"category"`
	Type              string             `json:"type"`
	Title             string             `json:"title"`
	Summary           pgtype.Text        `json:"summary"`
	PayloadJson       []byte             `json:"payload_json"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
}

type AgentTeam struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AgentTeamMember struct {
	ID               string             `json:"id"`
	TeamID           string             `json:"team_id"`
	AgentID          string             `json:"agent_id"`
	RoleKey          string             `json:"role_key"`
	CapabilitiesJson []byte             `json:"capabilities_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Approval struct {
	ID                 string             `json:"id"`
	MissionID          pgtype.Text        `json:"mission_id"`
	RunID              pgtype.Text        `json:"run_id"`
	NodeRunID          pgtype.Text        `json:"node_run_id"`
	Action             string             `json:"action"`
	SubjectType        string             `json:"subject_type"`
	SubjectID          string             `json:"subject_id"`
	IntentSnapshotJson []byte             `json:"intent_snapshot_json"`
	IntentHash         string             `json:"intent_hash"`
	Status             string             `json:"status"`
	Comment            pgtype.Text        `json:"comment"`
	CreatedBy          string             `json:"created_by"`
	DecidedBy          pgtype.Text        `json:"decided_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	DecidedAt          pgtype.Timestamptz `json:"decided_at"`
}

type ArtifactPublish struct {
	ID                string             `json:"id"`
	MissionID         pgtype.Text        `json:"mission_id"`
	ArtifactVersionID string             `json:"artifact_version_id"`
	ContentHash       string             `json:"content_hash"`
	BaseCommitSha     pgtype.Text        `json:"base_commit_sha"`
	IntentHash        string             `json:"intent_hash"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type DiscussionRound struct {
	ID                            string             `json:"id"`
	SessionID                     string             `json:"session_id"`
	RoundNo                       int32              `json:"round_no"`
	PromptSummary                 string             `json:"prompt_summary"`
	ParticipantAgentIdsJson       []byte             `json:"participant_agent_ids_json"`
	Summary                       string             `json:"summary"`
	OpenQuestionsJson             []byte             `json:"open_questions_json"`
	ConflictsJson                 []byte             `json:"conflicts_json"`
	ConclusionJson                []byte             `json:"conclusion_json"`
	AdoptedDocumentVersionIdsJson []byte             `json:"adopted_document_version_ids_json"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
}

type DiscussionSession struct {
	ID                 string             `json:"id"`
	MissionID          string             `json:"mission_id"`
	Topic              string             `json:"topic"`
	Status             string             `json:"status"`
	InitiatedByAgentID string             `json:"initiated_by_agent_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ClosedAt           pgtype.Timestamptz `json:"closed_at"`
}

type ExecutorProfile struct {
	ID                string             `json:"id"`
	ProjectID         string             `json:"project_id"`
	Name              string             `json:"name"`
	Type              string             `json:"type"`
	Command           string             `json:"command"`
	ArgsJson          []byte             `json:"args_json"`
	EnvSecretRefsJson []byte             `json:"env_secret_refs_json"`
	TimeoutSec        int32              `json:"timeout_sec"`
	MaxConcurrency    int32              `json:"max_concurrency"`
	MaxPromptChars    int32              `json:"max_prompt_chars"`
	AllowRepoRead     bool               `json:"allow_repo_read"`
	AllowRepoWrite    bool               `json:"allow_repo_write"`
	AllowNetwork      bool               `json:"allow_network"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ExecutorSession struct {
	ID                string             `json:"id"`
	MissionID         string             `json:"mission_id"`
	TaskItemID        pgtype.Text        `json:"task_item_id"`
	AgentID           string             `json:"agent_id"`
	ExecutorProfileID string             `json:"executor_profile_id"`
	Backend           string             `json:"backend"`
	Status            string             `json:"status"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
}

type ExecutorTranscript struct {
	ID                    string             `json:"id"`
	ExecutorSessionID     string             `json:"executor_session_id"`
	MissionID             string             `json:"mission_id"`
	AgentID               string             `json:"agent_id"`
	StorageKind           string             `json:"storage_kind"`
	RedactedObjectKey     pgtype.Text        `json:"redacted_object_key"`
	RawEncryptedObjectKey pgtype.Text        `json:"raw_encrypted_object_key"`
	Status                string             `json:"status"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	EndedAt               pgtype.Timestamptz `json:"ended_at"`
}

type ExecutorTranscriptEntry struct {
	ID           string             `json:"id"`
	TranscriptID string             `json:"transcript_id"`
	Seq          int32              `json:"seq"`
	Role         string             `json:"role"`
	EntryType    string             `json:"entry_type"`
	RedactedText pgtype.Text        `json:"redacted_text"`
	ContentJson  []byte             `json:"content_json"`
	RawObjectKey pgtype.Text        `json:"raw_object_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Mission struct {
	ID            string             `json:"id"`
	ProjectID     string             `json:"project_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	SourceType    string             `json:"source_type"`
	Status        string             `json:"status"`
	AdminAgentID  string             `json:"admin_agent_id"`
	TeamID        pgtype.Text        `json:"team_id"`
	RepoBindingID pgtype.Text        `json:"repo_binding_id"`
	CreatedBy     string             `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type MissionAgentRuntime struct {
	ID                       string             `json:"id"`
	MissionID                string             `json:"mission_id"`
	AgentID                  string             `json:"agent_id"`
	Status                   string             `json:"status"`
	CurrentTaskItemID        pgtype.Text        `json:"current_task_item_id"`
	CurrentRunID             pgtype.Text        `json:"current_run_id"`
	CurrentNodeRunID         pgtype.Text        `json:"current_node_run_id"`
	CurrentExecutorSessionID pgtype.Text        `json:"current_executor_session_id"`
	StatusSummary            pgtype.Text        `json:"status_summary"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type MissionArchive struct {
	ID                string             `json:"id"`
	MissionID         string             `json:"mission_id"`
	Status            string             `json:"status"`
	ManifestObjectKey pgtype.Text        `json:"manifest_object_key"`
	BundleObjectKey   pgtype.Text        `json:"bundle_object_key"`
	Hash              pgtype.Text        `json:"hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
}

type MissionDecision struct {
	ID                            string             `json:"id"`
	MissionID                     string             `json:"mission_id"`
	DecidedByAgentID              string             `json:"decided_by_agent_id"`
	Decision                      string             `json:"decision"`
	Summary                       string             `json:"summary"`
	RelatedTaskItemID             pgtype.Text        `json:"related_task_item_id"`
	RelatedDocumentVersionIdsJson []byte             `json:"related_document_version_ids_json"`
	RelatedRepoCandidateIdsJson   []byte             `json:"related_repo_candidate_ids_json"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
}

type MissionMember struct {
	ID        string             `json:"id"`
	MissionID string             `json:"mission_id"`
	AgentID   string             `json:"agent_id"`
	RoleKey   string             `json:"role_key"`
	IsAdmin   bool               `json:"is_admin"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type NodeRun struct {
	ID                string             `json:"id"`
	RunID             string             `json:"run_id"`
	NodeKey           string             `json:"node_key"`
	Status            string             `json:"status"`
	ExecutorSessionID pgtype.Text        `json:"executor_session_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
}

type Project struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RepoBinding struct {
	ID            string             `json:"id"`
	ProjectID     string             `json:"project_id"`
	Provider      string             `json:"provider"`
	RemoteUrl     string             `json:"remote_url"`
	DefaultBranch string             `json:"default_branch"`
	AuthMode      string             `json:"auth_mode"`
	WriteEnabled  bool               `json:"write_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RepoCandidate struct {
	ID                        string             `json:"id"`
	MissionID                 string             `json:"mission_id"`
	TaskItemID                pgtype.Text        `json:"task_item_id"`
	RepoBindingID             string             `json:"repo_binding_id"`
	BaseCommitSha             string             `json:"base_commit_sha"`
	ParentCandidateID         pgtype.Text        `json:"parent_candidate_id"`
	CreatedFrom               string             `json:"created_from"`
	CreatedFromRefID          string             `json:"created_from_ref_id"`
	TreeHash                  string             `json:"tree_hash"`
	PatchObjectKey            pgtype.Text        `json:"patch_object_key"`
	WorkspaceArchiveObjectKey pgtype.Text        `json:"workspace_archive_object_key"`
	Summary                   pgtype.Text        `json:"summary"`
	Status                    string             `json:"status"`
	ProducedByRunID           pgtype.Text        `json:"produced_by_run_id"`
	ProducedByNodeRunID       pgtype.Text        `json:"produced_by_node_run_id"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type RepoCandidatePublish struct {
	ID           string             `json:"id"`
	CandidateID  string             `json:"candidate_id"`
	IntentHash   string             `json:"intent_hash"`
	Status       string             `json:"status"`
	TargetBranch pgtype.Text        `json:"target_branch"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

type RepoSnapshot struct {
	ID            string             `json:"id"`
	MissionID     string             `json:"mission_id"`
	RepoBindingID pgtype.Text        `json:"repo_binding_id"`
	CommitSha     string             `json:"commit_sha"`
	RefName       pgtype.Text        `json:"ref_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ReviewCheckpoint struct {
	ID                           string             `json:"id"`
	MissionID                    string             `json:"mission_id"`
	TaskItemID                   pgtype.Text        `json:"task_item_id"`
	Kind                         string             `json:"kind"`
	RequestedByAgentID           string             `json:"requested_by_agent_id"`
	AssignedAgentID              pgtype.Text        `json:"assigned_agent_id"`
	Status                       string             `json:"status"`
	Summary                      pgtype.Text        `json:"summary"`
	LinkedDocumentVersionIdsJson []byte             `json:"linked_document_version_ids_json"`
	LinkedRepoCandidateIdsJson   []byte             `json:"linked_repo_candidate_ids_json"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	FinishedAt                   pgtype.Timestamptz `json:"finished_at"`
}

type Role struct {
	ID              string             `json:"id"`
	ProjectID       string             `json:"project_id"`
	Key             string             `json:"key"`
	Name            string             `json:"name"`
	PromptsJson     []byte             `json:"prompts_json"`
	PermissionsJson []byte             `json:"permissions_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Run struct {
	ID         string             `json:"id"`
	MissionID  string             `json:"mission_id"`
	TaskItemID pgtype.Text        `json:"task_item_id"`
	Status     string             `json:"status"`
	InputsJson []byte             `json:"inputs_json"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type RunArtifactInput struct {
	ID                string             `json:"id"`
	RunID             string             `json:"run_id"`
	ArtifactID        string             `json:"artifact_id"`
	ArtifactVersionID string             `json:"artifact_version_id"`
	Alias             pgtype.Text        `json:"alias"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type RuntimeObservabilityPolicy struct {
	ID                      string             `json:"id"`
	ProjectID               string             `json:"project_id"`
	AllowTranscriptView     bool               `json:"allow_transcript_view"`
	RedactSecretsByDefault  bool               `json:"redact_secrets_by_default"`
	AllowTranscriptExport   bool               `json:"allow_transcript_export"`
	RetainRuntimeEventsDays int32              `json:"retain_runtime_events_days"`
	RetainTranscriptDays    int32              `json:"retain_transcript_days"`
	ArchiveFullTranscript   bool               `json:"archive_full_transcript"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type SharedDocument struct {
	ID                      string             `json:"id"`
	MissionID               string             `json:"mission_id"`
	Kind                    string             `json:"kind"`
	Title                   string             `json:"title"`
	CurrentAdoptedVersionID pgtype.Text        `json:"current_adopted_version_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type SharedDocumentVersion struct {
	ID                string             `json:"id"`
	DocumentID        string             `json:"document_id"`
	Version           int32              `json:"version"`
	ParentVersionID   pgtype.Text        `json:"parent_version_id"`
	Status            string             `json:"status"`
	ContentFormat     string             `json:"content_format"`
	StorageKind       string             `json:"storage_kind"`
	ObjectKey         pgtype.Text        `json:"object_key"`
	ContentHash       string             `json:"content_hash"`
	ContentText       string             `json:"content_text"`
	ProducedByAgentID pgtype.Text        `json:"produced_by_agent_id"`
	ProducedByRunID   pgtype.Text        `json:"produced_by_run_id"`
	SourceRoundID     pgtype.Text        `json:"source_round_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type TaskBoard struct {
	ID        string             `json:"id"`
	MissionID string             `json:"mission_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TaskClaim struct {
	ID          string             `json:"id"`
	TaskItemID  string             `json:"task_item_id"`
	AgentID     string             `json:"agent_id"`
	Status      string             `json:"status"`
	ClaimReason pgtype.Text        `json:"claim_reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

type TaskHandoff struct {
	ID                           string             `json:"id"`
	TaskItemID                   string             `json:"task_item_id"`
	FromAgentID                  string             `json:"from_agent_id"`
	ToAgentID                    pgtype.Text        `json:"to_agent_id"`
	ToAdminAgent                 bool               `json:"to_admin_agent"`
	Summary                      string             `json:"summary"`
	OutputDocumentVersionIdsJson []byte             `json:"output_document_version_ids_json"`
	OutputRepoCandidateIdsJson   []byte             `json:"output_repo_candidate_ids_json"`
	OutputArtifactVersionIdsJson []byte             `json:"output_artifact_version_ids_json"`
	ValidationSummary            pgtype.Text        `json:"validation_summary"`
	RiskSummary                  pgtype.Text        `json:"risk_summary"`
	RecommendedNextAction        pgtype.Text        `json:"recommended_next_action"`
	Status                       string             `json:"status"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	DecidedAt                    pgtype.Timestamptz `json:"decided_at"`
}

type TaskItem struct {
	ID                          string             `json:"id"`
	BoardID                     string             `json:"board_id"`
	Title                       string             `json:"title"`
	Type                        string             `json:"type"`
	Status                      string             `json:"status"`
	AssignedAgentID             pgtype.Text        `json:"assigned_agent_id"`
	UpstreamTaskIdsJson         []byte             `json:"upstream_task_ids_json"`
	DownstreamTaskIdsJson       []byte             `json:"downstream_task_ids_json"`
	InputDocumentVersionIdsJson []byte             `json:"input_document_version_ids_json"`
	InputRepoCandidateIdsJson   []byte             `json:"input_repo_candidate_ids_json"`
	DefinitionOfDoneJson        []byte             `json:"definition_of_done_json"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

type TranscriptAccessAudit struct {
	ID           string             `json:"id"`
	TranscriptID string             `json:"transcript_id"`
	ActorUserID  string             `json:"actor_user_id"`
	AccessMode   string             `json:"access_mode"`
	Reason       pgtype.Text        `json:"reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
