// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                string             `json:"id"`
	ProjectID         string             `json:"project_id"`
	Name              string             `json:"name"`
	RoleID            string             `json:"role_id"`
	ExecutorProfileID string             `json:"executor_profile_id"`
	Enabled           bool               `json:"enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AgentTeam struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AgentTeamMember struct {
	ID               string             `json:"id"`
	TeamID           string             `json:"team_id"`
	AgentID          string             `json:"agent_id"`
	RoleKey          string             `json:"role_key"`
	CapabilitiesJson []byte             `json:"capabilities_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ExecutorProfile struct {
	ID                string             `json:"id"`
	ProjectID         string             `json:"project_id"`
	Name              string             `json:"name"`
	Type              string             `json:"type"`
	Command           string             `json:"command"`
	ArgsJson          []byte             `json:"args_json"`
	EnvSecretRefsJson []byte             `json:"env_secret_refs_json"`
	TimeoutSec        int32              `json:"timeout_sec"`
	MaxConcurrency    int32              `json:"max_concurrency"`
	MaxPromptChars    int32              `json:"max_prompt_chars"`
	AllowRepoRead     bool               `json:"allow_repo_read"`
	AllowRepoWrite    bool               `json:"allow_repo_write"`
	AllowNetwork      bool               `json:"allow_network"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RepoBinding struct {
	ID            string             `json:"id"`
	ProjectID     string             `json:"project_id"`
	Provider      string             `json:"provider"`
	RemoteUrl     string             `json:"remote_url"`
	DefaultBranch string             `json:"default_branch"`
	AuthMode      string             `json:"auth_mode"`
	WriteEnabled  bool               `json:"write_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID              string             `json:"id"`
	ProjectID       string             `json:"project_id"`
	Key             string             `json:"key"`
	Name            string             `json:"name"`
	PromptsJson     []byte             `json:"prompts_json"`
	PermissionsJson []byte             `json:"permissions_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
