// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo_candidates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepoCandidate = `-- name: CreateRepoCandidate :one
insert into repo_candidates (
  id,
  mission_id,
  task_item_id,
  repo_binding_id,
  base_commit_sha,
  parent_candidate_id,
  created_from,
  created_from_ref_id,
  tree_hash,
  patch_object_key,
  workspace_archive_object_key,
  summary,
  status,
  produced_by_run_id,
  produced_by_node_run_id
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
returning id, mission_id, task_item_id, repo_binding_id, base_commit_sha, parent_candidate_id, created_from, created_from_ref_id, tree_hash, patch_object_key, workspace_archive_object_key, summary, status, produced_by_run_id, produced_by_node_run_id, created_at
`

type CreateRepoCandidateParams struct {
	ID                        string      `json:"id"`
	MissionID                 string      `json:"mission_id"`
	TaskItemID                pgtype.Text `json:"task_item_id"`
	RepoBindingID             string      `json:"repo_binding_id"`
	BaseCommitSha             string      `json:"base_commit_sha"`
	ParentCandidateID         pgtype.Text `json:"parent_candidate_id"`
	CreatedFrom               string      `json:"created_from"`
	CreatedFromRefID          string      `json:"created_from_ref_id"`
	TreeHash                  string      `json:"tree_hash"`
	PatchObjectKey            pgtype.Text `json:"patch_object_key"`
	WorkspaceArchiveObjectKey pgtype.Text `json:"workspace_archive_object_key"`
	Summary                   pgtype.Text `json:"summary"`
	Status                    string      `json:"status"`
	ProducedByRunID           pgtype.Text `json:"produced_by_run_id"`
	ProducedByNodeRunID       pgtype.Text `json:"produced_by_node_run_id"`
}

func (q *Queries) CreateRepoCandidate(ctx context.Context, arg CreateRepoCandidateParams) (RepoCandidate, error) {
	row := q.db.QueryRow(ctx, createRepoCandidate,
		arg.ID,
		arg.MissionID,
		arg.TaskItemID,
		arg.RepoBindingID,
		arg.BaseCommitSha,
		arg.ParentCandidateID,
		arg.CreatedFrom,
		arg.CreatedFromRefID,
		arg.TreeHash,
		arg.PatchObjectKey,
		arg.WorkspaceArchiveObjectKey,
		arg.Summary,
		arg.Status,
		arg.ProducedByRunID,
		arg.ProducedByNodeRunID,
	)
	var i RepoCandidate
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.TaskItemID,
		&i.RepoBindingID,
		&i.BaseCommitSha,
		&i.ParentCandidateID,
		&i.CreatedFrom,
		&i.CreatedFromRefID,
		&i.TreeHash,
		&i.PatchObjectKey,
		&i.WorkspaceArchiveObjectKey,
		&i.Summary,
		&i.Status,
		&i.ProducedByRunID,
		&i.ProducedByNodeRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoCandidate = `-- name: GetRepoCandidate :one
select id, mission_id, task_item_id, repo_binding_id, base_commit_sha, parent_candidate_id, created_from, created_from_ref_id, tree_hash, patch_object_key, workspace_archive_object_key, summary, status, produced_by_run_id, produced_by_node_run_id, created_at
from repo_candidates
where id = $1
`

func (q *Queries) GetRepoCandidate(ctx context.Context, id string) (RepoCandidate, error) {
	row := q.db.QueryRow(ctx, getRepoCandidate, id)
	var i RepoCandidate
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.TaskItemID,
		&i.RepoBindingID,
		&i.BaseCommitSha,
		&i.ParentCandidateID,
		&i.CreatedFrom,
		&i.CreatedFromRefID,
		&i.TreeHash,
		&i.PatchObjectKey,
		&i.WorkspaceArchiveObjectKey,
		&i.Summary,
		&i.Status,
		&i.ProducedByRunID,
		&i.ProducedByNodeRunID,
		&i.CreatedAt,
	)
	return i, err
}
