// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNodeRun = `-- name: CreateNodeRun :one
insert into node_runs (
  id,
  run_id,
  node_key,
  status,
  executor_session_id
) values (
  $1, $2, $3, $4, $5
)
returning id, run_id, node_key, status, executor_session_id, created_at, started_at, finished_at
`

type CreateNodeRunParams struct {
	ID                string      `json:"id"`
	RunID             string      `json:"run_id"`
	NodeKey           string      `json:"node_key"`
	Status            string      `json:"status"`
	ExecutorSessionID pgtype.Text `json:"executor_session_id"`
}

func (q *Queries) CreateNodeRun(ctx context.Context, arg CreateNodeRunParams) (NodeRun, error) {
	row := q.db.QueryRow(ctx, createNodeRun,
		arg.ID,
		arg.RunID,
		arg.NodeKey,
		arg.Status,
		arg.ExecutorSessionID,
	)
	var i NodeRun
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NodeKey,
		&i.Status,
		&i.ExecutorSessionID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
insert into runs (
  id,
  mission_id,
  task_item_id,
  status,
  inputs_json
) values (
  $1, $2, $3, $4, $5
)
returning id, mission_id, task_item_id, status, inputs_json, created_at, started_at, finished_at
`

type CreateRunParams struct {
	ID         string      `json:"id"`
	MissionID  string      `json:"mission_id"`
	TaskItemID pgtype.Text `json:"task_item_id"`
	Status     string      `json:"status"`
	InputsJson []byte      `json:"inputs_json"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.MissionID,
		arg.TaskItemID,
		arg.Status,
		arg.InputsJson,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.TaskItemID,
		&i.Status,
		&i.InputsJson,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTaskClaimExecutionContext = `-- name: GetTaskClaimExecutionContext :one
select
  c.id as claim_id,
  b.mission_id,
  c.task_item_id,
  c.agent_id,
  m.admin_agent_id,
  t.title as task_title,
  t.type as task_type,
  t.downstream_task_ids_json,
  a.executor_profile_id,
  ep.command,
  ep.args_json
from task_claims c
join task_items t on t.id = c.task_item_id
join task_boards b on b.id = t.board_id
join missions m on m.id = b.mission_id
join agents a on a.id = c.agent_id
join executor_profiles ep on ep.id = a.executor_profile_id
where c.id = $1
`

type GetTaskClaimExecutionContextRow struct {
	ClaimID               string `json:"claim_id"`
	MissionID             string `json:"mission_id"`
	TaskItemID            string `json:"task_item_id"`
	AgentID               string `json:"agent_id"`
	AdminAgentID          string `json:"admin_agent_id"`
	TaskTitle             string `json:"task_title"`
	TaskType              string `json:"task_type"`
	DownstreamTaskIdsJson []byte `json:"downstream_task_ids_json"`
	ExecutorProfileID     string `json:"executor_profile_id"`
	Command               string `json:"command"`
	ArgsJson              []byte `json:"args_json"`
}

func (q *Queries) GetTaskClaimExecutionContext(ctx context.Context, id string) (GetTaskClaimExecutionContextRow, error) {
	row := q.db.QueryRow(ctx, getTaskClaimExecutionContext, id)
	var i GetTaskClaimExecutionContextRow
	err := row.Scan(
		&i.ClaimID,
		&i.MissionID,
		&i.TaskItemID,
		&i.AgentID,
		&i.AdminAgentID,
		&i.TaskTitle,
		&i.TaskType,
		&i.DownstreamTaskIdsJson,
		&i.ExecutorProfileID,
		&i.Command,
		&i.ArgsJson,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
update runs
set
  status = $2,
  finished_at = case when $2 in ('succeeded', 'failed', 'cancelled') then now() else finished_at end
where id = $1
returning id, mission_id, task_item_id, status, inputs_json, created_at, started_at, finished_at
`

type UpdateRunStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus, arg.ID, arg.Status)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.TaskItemID,
		&i.Status,
		&i.InputsJson,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
