// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentRuntimeEvent = `-- name: CreateAgentRuntimeEvent :one
insert into agent_runtime_events (
  id,
  mission_id,
  agent_id,
  executor_session_id,
  run_id,
  node_run_id,
  task_item_id,
  level,
  category,
  type,
  title,
  summary,
  payload_json
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
returning id, mission_id, agent_id, executor_session_id, run_id, node_run_id, task_item_id, level, category, type, title, summary, payload_json, occurred_at
`

type CreateAgentRuntimeEventParams struct {
	ID                string      `json:"id"`
	MissionID         string      `json:"mission_id"`
	AgentID           string      `json:"agent_id"`
	ExecutorSessionID string      `json:"executor_session_id"`
	RunID             pgtype.Text `json:"run_id"`
	NodeRunID         pgtype.Text `json:"node_run_id"`
	TaskItemID        pgtype.Text `json:"task_item_id"`
	Level             string      `json:"level"`
	Category          string      `json:"category"`
	Type              string      `json:"type"`
	Title             string      `json:"title"`
	Summary           pgtype.Text `json:"summary"`
	PayloadJson       []byte      `json:"payload_json"`
}

func (q *Queries) CreateAgentRuntimeEvent(ctx context.Context, arg CreateAgentRuntimeEventParams) (AgentRuntimeEvent, error) {
	row := q.db.QueryRow(ctx, createAgentRuntimeEvent,
		arg.ID,
		arg.MissionID,
		arg.AgentID,
		arg.ExecutorSessionID,
		arg.RunID,
		arg.NodeRunID,
		arg.TaskItemID,
		arg.Level,
		arg.Category,
		arg.Type,
		arg.Title,
		arg.Summary,
		arg.PayloadJson,
	)
	var i AgentRuntimeEvent
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.AgentID,
		&i.ExecutorSessionID,
		&i.RunID,
		&i.NodeRunID,
		&i.TaskItemID,
		&i.Level,
		&i.Category,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.PayloadJson,
		&i.OccurredAt,
	)
	return i, err
}

const createExecutorSession = `-- name: CreateExecutorSession :one
insert into executor_sessions (
  id,
  mission_id,
  task_item_id,
  agent_id,
  executor_profile_id,
  backend,
  status
) values (
  $1, $2, $3, $4, $5, $6, $7
)
returning id, mission_id, task_item_id, agent_id, executor_profile_id, backend, status, started_at, ended_at
`

type CreateExecutorSessionParams struct {
	ID                string      `json:"id"`
	MissionID         string      `json:"mission_id"`
	TaskItemID        pgtype.Text `json:"task_item_id"`
	AgentID           string      `json:"agent_id"`
	ExecutorProfileID string      `json:"executor_profile_id"`
	Backend           string      `json:"backend"`
	Status            string      `json:"status"`
}

func (q *Queries) CreateExecutorSession(ctx context.Context, arg CreateExecutorSessionParams) (ExecutorSession, error) {
	row := q.db.QueryRow(ctx, createExecutorSession,
		arg.ID,
		arg.MissionID,
		arg.TaskItemID,
		arg.AgentID,
		arg.ExecutorProfileID,
		arg.Backend,
		arg.Status,
	)
	var i ExecutorSession
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.TaskItemID,
		&i.AgentID,
		&i.ExecutorProfileID,
		&i.Backend,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createExecutorTranscript = `-- name: CreateExecutorTranscript :one
insert into executor_transcripts (
  id,
  executor_session_id,
  mission_id,
  agent_id,
  storage_kind,
  redacted_object_key,
  raw_encrypted_object_key,
  status
) values (
  $1, $2, $3, $4, $5, $6, $7, $8
)
returning id, executor_session_id, mission_id, agent_id, storage_kind, redacted_object_key, raw_encrypted_object_key, status, started_at, ended_at
`

type CreateExecutorTranscriptParams struct {
	ID                    string      `json:"id"`
	ExecutorSessionID     string      `json:"executor_session_id"`
	MissionID             string      `json:"mission_id"`
	AgentID               string      `json:"agent_id"`
	StorageKind           string      `json:"storage_kind"`
	RedactedObjectKey     pgtype.Text `json:"redacted_object_key"`
	RawEncryptedObjectKey pgtype.Text `json:"raw_encrypted_object_key"`
	Status                string      `json:"status"`
}

func (q *Queries) CreateExecutorTranscript(ctx context.Context, arg CreateExecutorTranscriptParams) (ExecutorTranscript, error) {
	row := q.db.QueryRow(ctx, createExecutorTranscript,
		arg.ID,
		arg.ExecutorSessionID,
		arg.MissionID,
		arg.AgentID,
		arg.StorageKind,
		arg.RedactedObjectKey,
		arg.RawEncryptedObjectKey,
		arg.Status,
	)
	var i ExecutorTranscript
	err := row.Scan(
		&i.ID,
		&i.ExecutorSessionID,
		&i.MissionID,
		&i.AgentID,
		&i.StorageKind,
		&i.RedactedObjectKey,
		&i.RawEncryptedObjectKey,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createExecutorTranscriptEntry = `-- name: CreateExecutorTranscriptEntry :one
insert into executor_transcript_entries (
  id,
  transcript_id,
  seq,
  role,
  entry_type,
  redacted_text,
  content_json,
  raw_object_key
) values (
  $1, $2, $3, $4, $5, $6, $7, $8
)
returning id, transcript_id, seq, role, entry_type, redacted_text, content_json, raw_object_key, created_at
`

type CreateExecutorTranscriptEntryParams struct {
	ID           string      `json:"id"`
	TranscriptID string      `json:"transcript_id"`
	Seq          int32       `json:"seq"`
	Role         string      `json:"role"`
	EntryType    string      `json:"entry_type"`
	RedactedText pgtype.Text `json:"redacted_text"`
	ContentJson  []byte      `json:"content_json"`
	RawObjectKey pgtype.Text `json:"raw_object_key"`
}

func (q *Queries) CreateExecutorTranscriptEntry(ctx context.Context, arg CreateExecutorTranscriptEntryParams) (ExecutorTranscriptEntry, error) {
	row := q.db.QueryRow(ctx, createExecutorTranscriptEntry,
		arg.ID,
		arg.TranscriptID,
		arg.Seq,
		arg.Role,
		arg.EntryType,
		arg.RedactedText,
		arg.ContentJson,
		arg.RawObjectKey,
	)
	var i ExecutorTranscriptEntry
	err := row.Scan(
		&i.ID,
		&i.TranscriptID,
		&i.Seq,
		&i.Role,
		&i.EntryType,
		&i.RedactedText,
		&i.ContentJson,
		&i.RawObjectKey,
		&i.CreatedAt,
	)
	return i, err
}

const createTranscriptAccessAudit = `-- name: CreateTranscriptAccessAudit :one
insert into transcript_access_audits (
  id,
  transcript_id,
  actor_user_id,
  access_mode,
  reason
) values (
  $1, $2, $3, $4, $5
)
returning id, transcript_id, actor_user_id, access_mode, reason, created_at
`

type CreateTranscriptAccessAuditParams struct {
	ID           string      `json:"id"`
	TranscriptID string      `json:"transcript_id"`
	ActorUserID  string      `json:"actor_user_id"`
	AccessMode   string      `json:"access_mode"`
	Reason       pgtype.Text `json:"reason"`
}

func (q *Queries) CreateTranscriptAccessAudit(ctx context.Context, arg CreateTranscriptAccessAuditParams) (TranscriptAccessAudit, error) {
	row := q.db.QueryRow(ctx, createTranscriptAccessAudit,
		arg.ID,
		arg.TranscriptID,
		arg.ActorUserID,
		arg.AccessMode,
		arg.Reason,
	)
	var i TranscriptAccessAudit
	err := row.Scan(
		&i.ID,
		&i.TranscriptID,
		&i.ActorUserID,
		&i.AccessMode,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutorSession = `-- name: GetExecutorSession :one
select id, mission_id, task_item_id, agent_id, executor_profile_id, backend, status, started_at, ended_at
from executor_sessions
where id = $1
`

func (q *Queries) GetExecutorSession(ctx context.Context, id string) (ExecutorSession, error) {
	row := q.db.QueryRow(ctx, getExecutorSession, id)
	var i ExecutorSession
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.TaskItemID,
		&i.AgentID,
		&i.ExecutorProfileID,
		&i.Backend,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getExecutorTranscriptBySession = `-- name: GetExecutorTranscriptBySession :one
select id, executor_session_id, mission_id, agent_id, storage_kind, redacted_object_key, raw_encrypted_object_key, status, started_at, ended_at
from executor_transcripts
where executor_session_id = $1
`

func (q *Queries) GetExecutorTranscriptBySession(ctx context.Context, executorSessionID string) (ExecutorTranscript, error) {
	row := q.db.QueryRow(ctx, getExecutorTranscriptBySession, executorSessionID)
	var i ExecutorTranscript
	err := row.Scan(
		&i.ID,
		&i.ExecutorSessionID,
		&i.MissionID,
		&i.AgentID,
		&i.StorageKind,
		&i.RedactedObjectKey,
		&i.RawEncryptedObjectKey,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getNextTranscriptEntrySeq = `-- name: GetNextTranscriptEntrySeq :one
select coalesce(max(seq), 0)::int4 + 1
from executor_transcript_entries
where transcript_id = $1
`

func (q *Queries) GetNextTranscriptEntrySeq(ctx context.Context, transcriptID string) (int32, error) {
	row := q.db.QueryRow(ctx, getNextTranscriptEntrySeq, transcriptID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listAgentRuntimeEventsBySession = `-- name: ListAgentRuntimeEventsBySession :many
select id, mission_id, agent_id, executor_session_id, run_id, node_run_id, task_item_id, level, category, type, title, summary, payload_json, occurred_at
from agent_runtime_events
where executor_session_id = $1
order by occurred_at asc
`

func (q *Queries) ListAgentRuntimeEventsBySession(ctx context.Context, executorSessionID string) ([]AgentRuntimeEvent, error) {
	rows, err := q.db.Query(ctx, listAgentRuntimeEventsBySession, executorSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRuntimeEvent
	for rows.Next() {
		var i AgentRuntimeEvent
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.AgentID,
			&i.ExecutorSessionID,
			&i.RunID,
			&i.NodeRunID,
			&i.TaskItemID,
			&i.Level,
			&i.Category,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.PayloadJson,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutorTranscriptEntriesBySession = `-- name: ListExecutorTranscriptEntriesBySession :many
select e.id, e.transcript_id, e.seq, e.role, e.entry_type, e.redacted_text, e.content_json, e.raw_object_key, e.created_at
from executor_transcript_entries e
join executor_transcripts t on t.id = e.transcript_id
where t.executor_session_id = $1
order by e.seq asc
`

func (q *Queries) ListExecutorTranscriptEntriesBySession(ctx context.Context, executorSessionID string) ([]ExecutorTranscriptEntry, error) {
	rows, err := q.db.Query(ctx, listExecutorTranscriptEntriesBySession, executorSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutorTranscriptEntry
	for rows.Next() {
		var i ExecutorTranscriptEntry
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.Seq,
			&i.Role,
			&i.EntryType,
			&i.RedactedText,
			&i.ContentJson,
			&i.RawObjectKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissionAgentRuntimes = `-- name: ListMissionAgentRuntimes :many
select id, mission_id, agent_id, status, current_task_item_id, current_run_id, current_node_run_id, current_executor_session_id, status_summary, started_at, updated_at
from mission_agent_runtimes
where mission_id = $1
order by updated_at desc
`

func (q *Queries) ListMissionAgentRuntimes(ctx context.Context, missionID string) ([]MissionAgentRuntime, error) {
	rows, err := q.db.Query(ctx, listMissionAgentRuntimes, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MissionAgentRuntime
	for rows.Next() {
		var i MissionAgentRuntime
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.AgentID,
			&i.Status,
			&i.CurrentTaskItemID,
			&i.CurrentRunID,
			&i.CurrentNodeRunID,
			&i.CurrentExecutorSessionID,
			&i.StatusSummary,
			&i.StartedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptAccessAuditsBySession = `-- name: ListTranscriptAccessAuditsBySession :many
select a.id, a.transcript_id, a.actor_user_id, a.access_mode, a.reason, a.created_at
from transcript_access_audits a
join executor_transcripts t on t.id = a.transcript_id
where t.executor_session_id = $1
order by a.created_at desc
`

func (q *Queries) ListTranscriptAccessAuditsBySession(ctx context.Context, executorSessionID string) ([]TranscriptAccessAudit, error) {
	rows, err := q.db.Query(ctx, listTranscriptAccessAuditsBySession, executorSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranscriptAccessAudit
	for rows.Next() {
		var i TranscriptAccessAudit
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.ActorUserID,
			&i.AccessMode,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutorSessionStatus = `-- name: UpdateExecutorSessionStatus :one
update executor_sessions
set
  status = $2,
  ended_at = case when $2 in ('completed', 'failed', 'cancelled') then now() else ended_at end
where id = $1
returning id, mission_id, task_item_id, agent_id, executor_profile_id, backend, status, started_at, ended_at
`

type UpdateExecutorSessionStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateExecutorSessionStatus(ctx context.Context, arg UpdateExecutorSessionStatusParams) (ExecutorSession, error) {
	row := q.db.QueryRow(ctx, updateExecutorSessionStatus, arg.ID, arg.Status)
	var i ExecutorSession
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.TaskItemID,
		&i.AgentID,
		&i.ExecutorProfileID,
		&i.Backend,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const updateExecutorTranscriptStatus = `-- name: UpdateExecutorTranscriptStatus :one
update executor_transcripts
set
  status = $2,
  ended_at = case when $2 = 'sealed' then now() else ended_at end
where id = $1
returning id, executor_session_id, mission_id, agent_id, storage_kind, redacted_object_key, raw_encrypted_object_key, status, started_at, ended_at
`

type UpdateExecutorTranscriptStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateExecutorTranscriptStatus(ctx context.Context, arg UpdateExecutorTranscriptStatusParams) (ExecutorTranscript, error) {
	row := q.db.QueryRow(ctx, updateExecutorTranscriptStatus, arg.ID, arg.Status)
	var i ExecutorTranscript
	err := row.Scan(
		&i.ID,
		&i.ExecutorSessionID,
		&i.MissionID,
		&i.AgentID,
		&i.StorageKind,
		&i.RedactedObjectKey,
		&i.RawEncryptedObjectKey,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const upsertAgentPresence = `-- name: UpsertAgentPresence :one
insert into agent_presences (
  agent_id,
  availability,
  current_mission_id,
  current_task_item_id,
  current_executor_session_id,
  last_heartbeat_at,
  updated_at
) values (
  $1, $2, $3, $4, $5, now(), now()
)
on conflict (agent_id) do update
set
  availability = excluded.availability,
  current_mission_id = excluded.current_mission_id,
  current_task_item_id = excluded.current_task_item_id,
  current_executor_session_id = excluded.current_executor_session_id,
  last_heartbeat_at = now(),
  updated_at = now()
returning agent_id, availability, current_mission_id, current_task_item_id, current_executor_session_id, last_heartbeat_at, updated_at
`

type UpsertAgentPresenceParams struct {
	AgentID                  string      `json:"agent_id"`
	Availability             string      `json:"availability"`
	CurrentMissionID         pgtype.Text `json:"current_mission_id"`
	CurrentTaskItemID        pgtype.Text `json:"current_task_item_id"`
	CurrentExecutorSessionID pgtype.Text `json:"current_executor_session_id"`
}

func (q *Queries) UpsertAgentPresence(ctx context.Context, arg UpsertAgentPresenceParams) (AgentPresence, error) {
	row := q.db.QueryRow(ctx, upsertAgentPresence,
		arg.AgentID,
		arg.Availability,
		arg.CurrentMissionID,
		arg.CurrentTaskItemID,
		arg.CurrentExecutorSessionID,
	)
	var i AgentPresence
	err := row.Scan(
		&i.AgentID,
		&i.Availability,
		&i.CurrentMissionID,
		&i.CurrentTaskItemID,
		&i.CurrentExecutorSessionID,
		&i.LastHeartbeatAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMissionAgentRuntime = `-- name: UpsertMissionAgentRuntime :one
insert into mission_agent_runtimes (
  id,
  mission_id,
  agent_id,
  status,
  current_task_item_id,
  current_run_id,
  current_node_run_id,
  current_executor_session_id,
  status_summary,
  started_at,
  updated_at
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now()
)
on conflict (mission_id, agent_id) do update
set
  status = excluded.status,
  current_task_item_id = excluded.current_task_item_id,
  current_run_id = excluded.current_run_id,
  current_node_run_id = excluded.current_node_run_id,
  current_executor_session_id = excluded.current_executor_session_id,
  status_summary = excluded.status_summary,
  started_at = coalesce(mission_agent_runtimes.started_at, excluded.started_at),
  updated_at = now()
returning id, mission_id, agent_id, status, current_task_item_id, current_run_id, current_node_run_id, current_executor_session_id, status_summary, started_at, updated_at
`

type UpsertMissionAgentRuntimeParams struct {
	ID                       string             `json:"id"`
	MissionID                string             `json:"mission_id"`
	AgentID                  string             `json:"agent_id"`
	Status                   string             `json:"status"`
	CurrentTaskItemID        pgtype.Text        `json:"current_task_item_id"`
	CurrentRunID             pgtype.Text        `json:"current_run_id"`
	CurrentNodeRunID         pgtype.Text        `json:"current_node_run_id"`
	CurrentExecutorSessionID pgtype.Text        `json:"current_executor_session_id"`
	StatusSummary            pgtype.Text        `json:"status_summary"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) UpsertMissionAgentRuntime(ctx context.Context, arg UpsertMissionAgentRuntimeParams) (MissionAgentRuntime, error) {
	row := q.db.QueryRow(ctx, upsertMissionAgentRuntime,
		arg.ID,
		arg.MissionID,
		arg.AgentID,
		arg.Status,
		arg.CurrentTaskItemID,
		arg.CurrentRunID,
		arg.CurrentNodeRunID,
		arg.CurrentExecutorSessionID,
		arg.StatusSummary,
		arg.StartedAt,
	)
	var i MissionAgentRuntime
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.AgentID,
		&i.Status,
		&i.CurrentTaskItemID,
		&i.CurrentRunID,
		&i.CurrentNodeRunID,
		&i.CurrentExecutorSessionID,
		&i.StatusSummary,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}
