// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireTaskClaimExecution = `-- name: AcquireTaskClaimExecution :one
update task_claims
set
  execution_lock_token = $2,
  attempt_count = attempt_count + 1,
  last_heartbeat_at = now()
where id = $1
  and status = 'active'
  and ended_at is null
  and (
    execution_lock_token is null
    or last_heartbeat_at < $3
  )
returning id, task_item_id, agent_id, status, claim_reason, created_at, ended_at
`

type AcquireTaskClaimExecutionParams struct {
	ID                 string             `json:"id"`
	ExecutionLockToken pgtype.Text        `json:"execution_lock_token"`
	LastHeartbeatAt    pgtype.Timestamptz `json:"last_heartbeat_at"`
}

type AcquireTaskClaimExecutionRow struct {
	ID          string             `json:"id"`
	TaskItemID  string             `json:"task_item_id"`
	AgentID     string             `json:"agent_id"`
	Status      string             `json:"status"`
	ClaimReason pgtype.Text        `json:"claim_reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) AcquireTaskClaimExecution(ctx context.Context, arg AcquireTaskClaimExecutionParams) (AcquireTaskClaimExecutionRow, error) {
	row := q.db.QueryRow(ctx, acquireTaskClaimExecution, arg.ID, arg.ExecutionLockToken, arg.LastHeartbeatAt)
	var i AcquireTaskClaimExecutionRow
	err := row.Scan(
		&i.ID,
		&i.TaskItemID,
		&i.AgentID,
		&i.Status,
		&i.ClaimReason,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const completeTaskClaim = `-- name: CompleteTaskClaim :one
update task_claims
set
  status = 'completed',
  execution_lock_token = null,
  last_error = null,
  ended_at = now()
where id = $1
returning id, task_item_id, agent_id, status, claim_reason, created_at, ended_at
`

type CompleteTaskClaimRow struct {
	ID          string             `json:"id"`
	TaskItemID  string             `json:"task_item_id"`
	AgentID     string             `json:"agent_id"`
	Status      string             `json:"status"`
	ClaimReason pgtype.Text        `json:"claim_reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CompleteTaskClaim(ctx context.Context, id string) (CompleteTaskClaimRow, error) {
	row := q.db.QueryRow(ctx, completeTaskClaim, id)
	var i CompleteTaskClaimRow
	err := row.Scan(
		&i.ID,
		&i.TaskItemID,
		&i.AgentID,
		&i.Status,
		&i.ClaimReason,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const createReviewCheckpoint = `-- name: CreateReviewCheckpoint :one
insert into review_checkpoints (
  id,
  mission_id,
  task_item_id,
  kind,
  requested_by_agent_id,
  assigned_agent_id,
  status,
  summary,
  linked_document_version_ids_json,
  linked_repo_candidate_ids_json
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
returning id, mission_id, task_item_id, kind, requested_by_agent_id, assigned_agent_id, status, summary, linked_document_version_ids_json, linked_repo_candidate_ids_json, created_at, finished_at
`

type CreateReviewCheckpointParams struct {
	ID                           string      `json:"id"`
	MissionID                    string      `json:"mission_id"`
	TaskItemID                   pgtype.Text `json:"task_item_id"`
	Kind                         string      `json:"kind"`
	RequestedByAgentID           string      `json:"requested_by_agent_id"`
	AssignedAgentID              pgtype.Text `json:"assigned_agent_id"`
	Status                       string      `json:"status"`
	Summary                      pgtype.Text `json:"summary"`
	LinkedDocumentVersionIdsJson []byte      `json:"linked_document_version_ids_json"`
	LinkedRepoCandidateIdsJson   []byte      `json:"linked_repo_candidate_ids_json"`
}

func (q *Queries) CreateReviewCheckpoint(ctx context.Context, arg CreateReviewCheckpointParams) (ReviewCheckpoint, error) {
	row := q.db.QueryRow(ctx, createReviewCheckpoint,
		arg.ID,
		arg.MissionID,
		arg.TaskItemID,
		arg.Kind,
		arg.RequestedByAgentID,
		arg.AssignedAgentID,
		arg.Status,
		arg.Summary,
		arg.LinkedDocumentVersionIdsJson,
		arg.LinkedRepoCandidateIdsJson,
	)
	var i ReviewCheckpoint
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.TaskItemID,
		&i.Kind,
		&i.RequestedByAgentID,
		&i.AssignedAgentID,
		&i.Status,
		&i.Summary,
		&i.LinkedDocumentVersionIdsJson,
		&i.LinkedRepoCandidateIdsJson,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createTaskBoard = `-- name: CreateTaskBoard :one
insert into task_boards (
  id,
  mission_id,
  title
) values (
  $1, $2, $3
)
returning id, mission_id, title, created_at, updated_at
`

type CreateTaskBoardParams struct {
	ID        string `json:"id"`
	MissionID string `json:"mission_id"`
	Title     string `json:"title"`
}

func (q *Queries) CreateTaskBoard(ctx context.Context, arg CreateTaskBoardParams) (TaskBoard, error) {
	row := q.db.QueryRow(ctx, createTaskBoard, arg.ID, arg.MissionID, arg.Title)
	var i TaskBoard
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskClaim = `-- name: CreateTaskClaim :one
insert into task_claims (
  id,
  task_item_id,
  agent_id,
  status,
  claim_reason
) values (
  $1, $2, $3, $4, $5
)
returning id, task_item_id, agent_id, status, claim_reason, created_at, ended_at
`

type CreateTaskClaimParams struct {
	ID          string      `json:"id"`
	TaskItemID  string      `json:"task_item_id"`
	AgentID     string      `json:"agent_id"`
	Status      string      `json:"status"`
	ClaimReason pgtype.Text `json:"claim_reason"`
}

type CreateTaskClaimRow struct {
	ID          string             `json:"id"`
	TaskItemID  string             `json:"task_item_id"`
	AgentID     string             `json:"agent_id"`
	Status      string             `json:"status"`
	ClaimReason pgtype.Text        `json:"claim_reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CreateTaskClaim(ctx context.Context, arg CreateTaskClaimParams) (CreateTaskClaimRow, error) {
	row := q.db.QueryRow(ctx, createTaskClaim,
		arg.ID,
		arg.TaskItemID,
		arg.AgentID,
		arg.Status,
		arg.ClaimReason,
	)
	var i CreateTaskClaimRow
	err := row.Scan(
		&i.ID,
		&i.TaskItemID,
		&i.AgentID,
		&i.Status,
		&i.ClaimReason,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const createTaskHandoff = `-- name: CreateTaskHandoff :one
insert into task_handoffs (
  id,
  task_item_id,
  from_agent_id,
  to_agent_id,
  to_admin_agent,
  summary,
  output_document_version_ids_json,
  output_repo_candidate_ids_json,
  output_artifact_version_ids_json,
  validation_summary,
  risk_summary,
  recommended_next_action,
  status
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
returning id, task_item_id, from_agent_id, to_agent_id, to_admin_agent, summary, output_document_version_ids_json, output_repo_candidate_ids_json, output_artifact_version_ids_json, validation_summary, risk_summary, recommended_next_action, status, created_at, decided_at
`

type CreateTaskHandoffParams struct {
	ID                           string      `json:"id"`
	TaskItemID                   string      `json:"task_item_id"`
	FromAgentID                  string      `json:"from_agent_id"`
	ToAgentID                    pgtype.Text `json:"to_agent_id"`
	ToAdminAgent                 bool        `json:"to_admin_agent"`
	Summary                      string      `json:"summary"`
	OutputDocumentVersionIdsJson []byte      `json:"output_document_version_ids_json"`
	OutputRepoCandidateIdsJson   []byte      `json:"output_repo_candidate_ids_json"`
	OutputArtifactVersionIdsJson []byte      `json:"output_artifact_version_ids_json"`
	ValidationSummary            pgtype.Text `json:"validation_summary"`
	RiskSummary                  pgtype.Text `json:"risk_summary"`
	RecommendedNextAction        pgtype.Text `json:"recommended_next_action"`
	Status                       string      `json:"status"`
}

func (q *Queries) CreateTaskHandoff(ctx context.Context, arg CreateTaskHandoffParams) (TaskHandoff, error) {
	row := q.db.QueryRow(ctx, createTaskHandoff,
		arg.ID,
		arg.TaskItemID,
		arg.FromAgentID,
		arg.ToAgentID,
		arg.ToAdminAgent,
		arg.Summary,
		arg.OutputDocumentVersionIdsJson,
		arg.OutputRepoCandidateIdsJson,
		arg.OutputArtifactVersionIdsJson,
		arg.ValidationSummary,
		arg.RiskSummary,
		arg.RecommendedNextAction,
		arg.Status,
	)
	var i TaskHandoff
	err := row.Scan(
		&i.ID,
		&i.TaskItemID,
		&i.FromAgentID,
		&i.ToAgentID,
		&i.ToAdminAgent,
		&i.Summary,
		&i.OutputDocumentVersionIdsJson,
		&i.OutputRepoCandidateIdsJson,
		&i.OutputArtifactVersionIdsJson,
		&i.ValidationSummary,
		&i.RiskSummary,
		&i.RecommendedNextAction,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const createTaskItem = `-- name: CreateTaskItem :one
insert into task_items (
  id,
  board_id,
  title,
  type,
  status,
  assigned_agent_id,
  upstream_task_ids_json,
  downstream_task_ids_json,
  input_document_version_ids_json,
  input_repo_candidate_ids_json,
  definition_of_done_json
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
returning id, board_id, title, type, status, assigned_agent_id, upstream_task_ids_json, downstream_task_ids_json, input_document_version_ids_json, input_repo_candidate_ids_json, definition_of_done_json, created_at, updated_at
`

type CreateTaskItemParams struct {
	ID                          string      `json:"id"`
	BoardID                     string      `json:"board_id"`
	Title                       string      `json:"title"`
	Type                        string      `json:"type"`
	Status                      string      `json:"status"`
	AssignedAgentID             pgtype.Text `json:"assigned_agent_id"`
	UpstreamTaskIdsJson         []byte      `json:"upstream_task_ids_json"`
	DownstreamTaskIdsJson       []byte      `json:"downstream_task_ids_json"`
	InputDocumentVersionIdsJson []byte      `json:"input_document_version_ids_json"`
	InputRepoCandidateIdsJson   []byte      `json:"input_repo_candidate_ids_json"`
	DefinitionOfDoneJson        []byte      `json:"definition_of_done_json"`
}

func (q *Queries) CreateTaskItem(ctx context.Context, arg CreateTaskItemParams) (TaskItem, error) {
	row := q.db.QueryRow(ctx, createTaskItem,
		arg.ID,
		arg.BoardID,
		arg.Title,
		arg.Type,
		arg.Status,
		arg.AssignedAgentID,
		arg.UpstreamTaskIdsJson,
		arg.DownstreamTaskIdsJson,
		arg.InputDocumentVersionIdsJson,
		arg.InputRepoCandidateIdsJson,
		arg.DefinitionOfDoneJson,
	)
	var i TaskItem
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.AssignedAgentID,
		&i.UpstreamTaskIdsJson,
		&i.DownstreamTaskIdsJson,
		&i.InputDocumentVersionIdsJson,
		&i.InputRepoCandidateIdsJson,
		&i.DefinitionOfDoneJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failTaskClaimExecution = `-- name: FailTaskClaimExecution :one
update task_claims
set
  status = case when attempt_count >= $2 then 'failed' else 'active' end,
  execution_lock_token = null,
  last_error = $3,
  last_heartbeat_at = now(),
  ended_at = case when attempt_count >= $2 then now() else null end
where id = $1
returning id, task_item_id, agent_id, status, claim_reason, created_at, ended_at
`

type FailTaskClaimExecutionParams struct {
	ID           string      `json:"id"`
	AttemptCount int32       `json:"attempt_count"`
	LastError    pgtype.Text `json:"last_error"`
}

type FailTaskClaimExecutionRow struct {
	ID          string             `json:"id"`
	TaskItemID  string             `json:"task_item_id"`
	AgentID     string             `json:"agent_id"`
	Status      string             `json:"status"`
	ClaimReason pgtype.Text        `json:"claim_reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) FailTaskClaimExecution(ctx context.Context, arg FailTaskClaimExecutionParams) (FailTaskClaimExecutionRow, error) {
	row := q.db.QueryRow(ctx, failTaskClaimExecution, arg.ID, arg.AttemptCount, arg.LastError)
	var i FailTaskClaimExecutionRow
	err := row.Scan(
		&i.ID,
		&i.TaskItemID,
		&i.AgentID,
		&i.Status,
		&i.ClaimReason,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getLatestTaskBoardByMission = `-- name: GetLatestTaskBoardByMission :one
select id, mission_id, title, created_at, updated_at
from task_boards
where mission_id = $1
order by created_at desc
limit 1
`

func (q *Queries) GetLatestTaskBoardByMission(ctx context.Context, missionID string) (TaskBoard, error) {
	row := q.db.QueryRow(ctx, getLatestTaskBoardByMission, missionID)
	var i TaskBoard
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskItem = `-- name: GetTaskItem :one
select id, board_id, title, type, status, assigned_agent_id, upstream_task_ids_json, downstream_task_ids_json, input_document_version_ids_json, input_repo_candidate_ids_json, definition_of_done_json, created_at, updated_at
from task_items
where id = $1
`

func (q *Queries) GetTaskItem(ctx context.Context, id string) (TaskItem, error) {
	row := q.db.QueryRow(ctx, getTaskItem, id)
	var i TaskItem
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.AssignedAgentID,
		&i.UpstreamTaskIdsJson,
		&i.DownstreamTaskIdsJson,
		&i.InputDocumentVersionIdsJson,
		&i.InputRepoCandidateIdsJson,
		&i.DefinitionOfDoneJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTaskClaimIDs = `-- name: ListActiveTaskClaimIDs :many
select id
from task_claims
where status = 'active'
  and ended_at is null
order by created_at asc
`

func (q *Queries) ListActiveTaskClaimIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveTaskClaimIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskItemsByBoard = `-- name: ListTaskItemsByBoard :many
select id, board_id, title, type, status, assigned_agent_id, upstream_task_ids_json, downstream_task_ids_json, input_document_version_ids_json, input_repo_candidate_ids_json, definition_of_done_json, created_at, updated_at
from task_items
where board_id = $1
order by created_at asc
`

func (q *Queries) ListTaskItemsByBoard(ctx context.Context, boardID string) ([]TaskItem, error) {
	rows, err := q.db.Query(ctx, listTaskItemsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskItem
	for rows.Next() {
		var i TaskItem
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.AssignedAgentID,
			&i.UpstreamTaskIdsJson,
			&i.DownstreamTaskIdsJson,
			&i.InputDocumentVersionIdsJson,
			&i.InputRepoCandidateIdsJson,
			&i.DefinitionOfDoneJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTaskClaimExecution = `-- name: ReleaseTaskClaimExecution :one
update task_claims
set
  execution_lock_token = null,
  last_heartbeat_at = now()
where id = $1
returning id, task_item_id, agent_id, status, claim_reason, created_at, ended_at
`

type ReleaseTaskClaimExecutionRow struct {
	ID          string             `json:"id"`
	TaskItemID  string             `json:"task_item_id"`
	AgentID     string             `json:"agent_id"`
	Status      string             `json:"status"`
	ClaimReason pgtype.Text        `json:"claim_reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) ReleaseTaskClaimExecution(ctx context.Context, id string) (ReleaseTaskClaimExecutionRow, error) {
	row := q.db.QueryRow(ctx, releaseTaskClaimExecution, id)
	var i ReleaseTaskClaimExecutionRow
	err := row.Scan(
		&i.ID,
		&i.TaskItemID,
		&i.AgentID,
		&i.Status,
		&i.ClaimReason,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const updateTaskClaimHeartbeat = `-- name: UpdateTaskClaimHeartbeat :one
update task_claims
set
  last_heartbeat_at = now()
where id = $1
  and execution_lock_token = $2
returning id, task_item_id, agent_id, status, claim_reason, created_at, ended_at
`

type UpdateTaskClaimHeartbeatParams struct {
	ID                 string      `json:"id"`
	ExecutionLockToken pgtype.Text `json:"execution_lock_token"`
}

type UpdateTaskClaimHeartbeatRow struct {
	ID          string             `json:"id"`
	TaskItemID  string             `json:"task_item_id"`
	AgentID     string             `json:"agent_id"`
	Status      string             `json:"status"`
	ClaimReason pgtype.Text        `json:"claim_reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) UpdateTaskClaimHeartbeat(ctx context.Context, arg UpdateTaskClaimHeartbeatParams) (UpdateTaskClaimHeartbeatRow, error) {
	row := q.db.QueryRow(ctx, updateTaskClaimHeartbeat, arg.ID, arg.ExecutionLockToken)
	var i UpdateTaskClaimHeartbeatRow
	err := row.Scan(
		&i.ID,
		&i.TaskItemID,
		&i.AgentID,
		&i.Status,
		&i.ClaimReason,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const updateTaskItemStatus = `-- name: UpdateTaskItemStatus :one
update task_items
set
  status = $2,
  updated_at = now()
where id = $1
returning id, board_id, title, type, status, assigned_agent_id, upstream_task_ids_json, downstream_task_ids_json, input_document_version_ids_json, input_repo_candidate_ids_json, definition_of_done_json, created_at, updated_at
`

type UpdateTaskItemStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTaskItemStatus(ctx context.Context, arg UpdateTaskItemStatusParams) (TaskItem, error) {
	row := q.db.QueryRow(ctx, updateTaskItemStatus, arg.ID, arg.Status)
	var i TaskItem
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.AssignedAgentID,
		&i.UpstreamTaskIdsJson,
		&i.DownstreamTaskIdsJson,
		&i.InputDocumentVersionIdsJson,
		&i.InputRepoCandidateIdsJson,
		&i.DefinitionOfDoneJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
